# Generated by Django 5.1 on 2024-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_genre_movie_genres_remove_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
